version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lar_vidu1_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www